project:
  type: website

website:
  title: "PythonistaMX"
  description: "Sitio de la comunidad PythonistaMX"
  
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca de
      - href: blog/index.qmd
        text: Blog

  sidebar:
    - title: "Navegación"
      contents:
        - href: index.qmd
          text: Inicio
        - href: about.qmd
          text: Acerca de

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto